# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db62c8fbbc424fea3f27452f21f5aafc734cbd77822909c6f92f34de1e16406b6118afa81800c314eba83a08940e0f00fc79e834c7812aac78d60be3c4358261

test:
  secret_key_base: dcfd299a877ba8d1820f894d99c058bb7ce5600493993f707a1aee7178993960d8cfe5c1efbfad3d1274ab54298f118eb1c1a3f9c5d73523a7db32378dffa754

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
